### ISSUE TITLE
Custom error messages

### ISSUE THREAD

**Issue by bryanjtc** [gcascio/next-intl-zod#1]
Is there a way to do the same as zod-i18n for custom error translations? https://github.com/aiji42/zod-i18n#custom-errors
Any suggestions or alternative?

**Comment by gcascio** [comment]
Hi, yes that is possible! I added an example approach, checkout this [commit](https://github.com/gcascio/next-intl-zod/commit/8732cdfc6a94479861c118be6fd2cf2cf436facb).
